### ISSUE TITLE
Investigate multithreading

### ISSUE THREAD

**Issue by jeep70** [jeep70/qView#127]

**Comment by jeep70** [comment]
Something to get it's own thread would definitely be animatedframechange, it runs slow

**Comment by jeep70** [comment]
It seems like you can't do QPixmap operations in seperate threads with Qt, so this is a wash. The only workaround is converting to QImage and back, but that'll probably result in similar performance anyway as conversion is an expensive operation.

**Comment by easymodo** [comment]
Well, not really. I managed to completely eliminate stutteting in qimgv that way. Except that I initially load into qimage. The only downside is that you'll have to keep 2 copies in memory (image and pixmap).

The ideal solution would be probably opengl. I wrote a basic viewer with it for testing purposes and shit's pretty fast

**Comment by jeep70** [comment]
How did you do OpenGL? I tried to implement it into qView but it ended up performing very badly see #43

**Comment by easymodo** [comment]
I'm using OpenCV to load, store & scale image, then draw it in QOpenGLWidget. I've turned to opengl so i could display cv::Mat directly without converting it to qpixmap beforehand

**Comment by jeep70** [comment]
Maybe i'll give that a try sometime in the future

**Comment by jeep70** [comment]
The applications of multithreading in the future will have their own issues
