### ISSUE TITLE
scale window to image size

### ISSUE THREAD

**Issue by kupiqu** [jeep70/qView#154]
Nice work.

I'd like to use qview mostly as a pseudo image preview app, called from dolphin servicemenu. For this I wish there was an option to be able to scale its window size to the image content size (taking into account the scale factor parameter).

**Comment by jeep70** [comment]
What exactly do you mean by "taking into account the scale factor parameter"?

**Comment by kupiqu** [comment]
I meant current parameter in tools >  options > Scale factor, which default value is 25%

**Comment by jeep70** [comment]
That controls how far each zoom step is. Are you asking for an option to make the window size a percentage of the image's actual size?

**Comment by jeep70** [comment]
Ok, I see your edit. I think I can do that

**Comment by kupiqu** [comment]
> That controls how far each zoom step is.

I see, I got that wrong.

My original request is to scale the window to the image size.

Now I see that for huge images, it would also be nice to scale them down. I guess a maximum size (proportional to the screen size) would be good for that

**Comment by jeep70** [comment]
Ok, got it, thanks

**Comment by jeep70** [comment]
Should be implemented in 60b3e1e6f871cefce4057e5cf59ee55182a0d69f - give it a try and tell me if it works for you!

**Comment by kupiqu** [comment]
Wow, it works great, congratulations!

Two further suggestions in this context:

1. qView would offer a great experience if the window location would keep its center when using "window matches image size: -> when opening images" as this would avoid the feeling of the window jumping around from image to image.

2. When setting the boundaries "up to", what about having the option to use a % of the screensize?

Point 2 is not that important compared to 1 IMO, I just modified the size in px to match the % I want, but I guess it would ease this for some users.

Finally, as images are shown continuously in a loop, I'd also like to suggest displaying a transient animation notifying that the loop has restarted.

**Comment by kupiqu** [comment]
> 2. When setting the boundaries "up to", what about having the option to use a % of the screensize?

This would be particularly useful/efficient for systems with 2+ monitors though

**Comment by kupiqu** [comment]
> 1. done

Excellent!

> 2. I thought about doing this, but I concluded that it would be better overall to have an option for the dimensions because
> 
> * It offers more potential customization for edge cases
> * you can just calculate it yourself and put it in (the default value is 90% of the primary screen res)

Yes, I agree on this for single screen systems, but I still think it would be very useful for dual monitor systems, so it just works as expected irrespective of screen resolution, otherwise window size may be too big or small or need continous readjustment of the setting.

3. I don't think this would really be right for qView. You can tell when the folder has looped around from the display in the new verbose titlebar.

Fair enough. I prefer not using verbose window titles because I use an application applet (together with the globalmenu) which reads out the window title, and I don't want it to be verbose.

> Perhaps an option to disallow looping through folders would be good though.

I was about to suggest this alternative too. So one can move forward and backward but not around. I think this could be a good compromise.

**Comment by kupiqu** [comment]
> 1. done

It is really a very much improved experience. Thanks for implementing!

Unfortunately, I see a bit of an artifact in each image transition.

a. if the two images have the same size, there is still a bit of a (tiny) up-left shift. Can you please try to reproduce it?

b. if the two images have different size, it seems that the first image is a scaled to the new size and then that image is replaced by the new one. It would be nice to first mask the original image with the background color, then resize and finally replace the mask by the new image. I think it would be more visually appealing.

**Comment by jeep70** [comment]
1a. Should be fixed but I really should test on other platforms cause I used a pretty [hacky](https://user-images.githubusercontent.com/10716694/47113839-135a2600-d228-11e8-8ae4-0e4384b6fd53.png) solution
1b. I tried to improve it a little by doing it before running `resetScale()` but I don't think I can do much better without rewriting a lot of scaling code
2. You actually have a great point, so I changed it over to the percentage. The only bad thing about this is that the minimum Qt version will rise to Qt 5.10
3. The option should be implemented now

**Comment by jeep70** [comment]
okay, 1a definitely still exists

**Comment by jeep70** [comment]
Fixed now 9b169be41ff2d097de61f0534cc541941422993e

**Comment by kupiqu** [comment]
The 1a change fixed the up-left shift I was experiencing, but funnily enough the up shift changed into a right shift

**Comment by kupiqu** [comment]
> Fixed now [9b169be](https://github.com/jeep70/qView/commit/9b169be41ff2d097de61f0534cc541941422993e)

I'll check it out... :)

**Comment by kupiqu** [comment]
Excellent, great work!

The only remaining issue is 1b, but it seems it's difficult to fix. Should we leave this issue closed, or open as a reminder?

**Comment by jeep70** [comment]
I will close this issue and open another issue about this problem - I will be doing some rewriting of the loading code in the future so I might sneak it in if I can.

Thanks for all your help.
