### ISSUE TITLE
Previous frame is extremely slow with long gifs

### ISSUE THREAD

**Issue by jeep70** [jeep70/qView#159]
only idea i have for now is add an option to cache all frames (will use *way* more memory, but go to previous frame perfectly smoothly)
It works totally fine on short gifs so I won't be removing the feature all together

**Comment by jeep70** [comment]
Scratch that - four options here

1. Implement it in a way that it freezes every frame change, with especially long freezes for longer gifs
2. Implement it in a way where it zooms forward in the image from frame 0 to the frame before the one you were at
3. Implement it in a way where it works fine but takes up a ton of ram (i've seen 600MB)
4. Not implement it

Guess which one I'm leaning towards (it's 4)

**Comment by Thespikedballofdoom** [comment]
waaa
