### ISSUE TITLE
Document limitations

### ISSUE THREAD

**Issue by dumblob** [jeep70/qView#167]
I'm working with high-resolution bitmaps which might require special handling (cache hierarchy - graphics memory, RAM, persistent storage).

What is the maximum width (internally there are usually scanlines of a fixed length), what is the maximum height, what are the supported bit depths (1bit, indexed palette with 8/16 bits, grayscale, 24bit, 32bit), what are the supported compression algorithms (e.g. TIFF supports Deflate, RLL, etc.). Are there any other limitations of this software? If the limits differ for certain platforms, please make a matrix with all the differences.

**Comment by jeep70** [comment]
I've personally tested up to 10,000x10,000 images and they worked totally fine. I'm not sure about the more technical things, but I'm just using Qt5's built in QPixmap class for storing and processing, so the limitations of qView should be the same as the limitations of QPixmap.
