### ISSUE TITLE
Image shown in wrong rotation when taken by camer sideways or upside down

### ISSUE THREAD

**Issue by xiegeo** [jeep70/qView#168]
os: win10, version: 1.0

This image is shown upside down.
![error](https://user-images.githubusercontent.com/3104386/46186413-4b0e2780-c293-11e8-8427-f27abb95f141.png)

Image files to reproduce the problem:
[samples.zip](https://github.com/jeep70/qView/files/2426663/samples.zip)

**Comment by jeep70** [comment]
related to #94 - needs to take the orientation from exif data and adjust accordingly

**Comment by jeep70** [comment]
actually, extremely easy to fix on it's own using [this](http://doc.qt.io/qt-5/qimagereader.html#setAutoTransform)
